import { ExceptionCode } from '../payloads';

export const EXCEPTION_LEVEL = {
  CRITICAL: 'critical',
  NORMAL: 'normal',
  HACK: 'hack',
};

export const EXCEPTION_TYPE = {
  AUTH: 'authentication',
  AUTHOR: 'authorization',
  REQUEST_ERROR: 'request_error',
  NOT_POSSIBLE_INPUT: 'not_possible_input',
  EXTERNAL_SERVICE_ERROR: 'external_service_error',
  UNEXPECTED: 'unexpected',
};

export const EXCEPTION_CODE = {
  USER_SESSION_NOT_FOUND: new ExceptionCode(
    'UserSessionNotFound',
    4002,
    'User Session Not found',
    EXCEPTION_TYPE.AUTH,
    EXCEPTION_LEVEL.NORMAL,
    401,
  ),
  NOT_SELECTED_DATABASE: new ExceptionCode(
    'NotSelectDatabase',
    4003,
    'Please select Database',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
    400,
  ),
  SELECTED_DATABASE_DOES_NOT_EXIST: new ExceptionCode(
    'SelectedDatabaseDoesNotExist',
    4005,
    'Selected Database does not exist, please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
    400,
  ),
  VARIANT_RESULT_REJECTED: new ExceptionCode(
    'VariantResultRejected',
    4006,
    'Database Error! Please contact admin. Thank you.',
    EXCEPTION_TYPE.UNEXPECTED,
    EXCEPTION_LEVEL.CRITICAL,
  ),
  EXPORT_VARIANT_RESULT_REJECTED: new ExceptionCode(
    'ExportVariantResultRejected',
    4007,
    'Database Error! Please contact admin. Thank you.',
    EXCEPTION_TYPE.UNEXPECTED,
    EXCEPTION_LEVEL.CRITICAL,
  ),
  GET_S3_PRESIGNED_URL_REJECTED: new ExceptionCode(
    'GetS3PresignedUrlRejected',
    4008,
    'S3 Error! Please contact admin. Thank you.',
    EXCEPTION_TYPE.EXTERNAL_SERVICE_ERROR,
    EXCEPTION_LEVEL.CRITICAL,
  ),
  GET_S3_SAMPLE_NOT_FOUND: new ExceptionCode(
    'GetS3SampleNotFound',
    4009,
    'Sample Error! Please contact admin. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.CRITICAL,
  ),
  UPDATE_OUTDATED_DOCUMENT: new ExceptionCode(
    'UpdateOutdatedDocument',
    4010,
    'Current project trying to update is not up-to-date, page will reload.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
    400,
  ),
  SELECTED_PROJECT_DOES_NOT_EXIST: new ExceptionCode(
    'SelectedProjectDoesNotExist',
    4011,
    'Selected Project does not exist, please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
    400,
  ),
  SELECTED_DATABASE_DOES_NOT_EXIST_IN_PROJECT: new ExceptionCode(
    'SelectedDatabaseDoesNotExistInProject',
    4012,
    'Selected Database does not exist in current project, please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
    400,
  ),
  DUPLICATED_SAMPLES_IN_PROJECT: new ExceptionCode(
    'DuplicatedSamplesInProject',
    4013,
    'Duplicated Samples in same project. Please contact admin. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
  ),
  DATABSE_ALREADY_EXISTS: new ExceptionCode(
    'databseAlreadyExists',
    4014,
    'Databases attended to add already exists in project. Please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
  ),
  DATABSE_NOT_EXISTS: new ExceptionCode(
    'databseNotExists',
    4015,
    'Databases attended to delete does not exist in project. Please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
  ),
  NOT_VALID_DB_STATUS: new ExceptionCode(
    'notValidDbStatus',
    4016,
    'The chosen status is not a valid status. Please choose again. Thank you.',
    EXCEPTION_TYPE.NOT_POSSIBLE_INPUT,
    EXCEPTION_LEVEL.HACK,
  ),
  NOT_VALID_PED_FILE: new ExceptionCode(
    'notValidPedFile',
    4017,
    'The PED file format is not correct. Please follow the https://gatk.broadinstitute.org/hc/en-us/articles/360035531972-PED-Pedigree-format. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  NOT_VALID_HPO_FILE: new ExceptionCode(
    'notValidHpoFile',
    4018,
    'The HPO file format is not correct. Each row is one HPO terms. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  NOT_VALID_SNP_VCF_FILE: new ExceptionCode(
    'notValidSnpVcfFile',
    4019,
    'The SNP file format is not correct. Please follow the https://samtools.github.io/hts-specs/VCFv4.4.pdf and gzip it. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  NOT_VALID_SV_VCF_FILE: new ExceptionCode(
    'notValidSvVcfFile',
    4020,
    'The SV file format is not correct. Please follow the https://samtools.github.io/hts-specs/VCFv4.4.pdf and gzip it. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  AT_LEAST_ONE_VARIANT_TYPE: new ExceptionCode(
    'atleastOneVariantType',
    4021,
    'Please upload at least one variant type either SNP or SV VCF file. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  PIPELINE_REQUIRE_PED: new ExceptionCode(
    'pipelineRequirePed',
    4022,
    'Please upload PED file for annotation pipeline. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  PIPELINE_REQUIRE_HPO_FILE: new ExceptionCode(
    'pipelineRequireHpoFile',
    4023,
    'Please upload HPO file for annotation pipeline. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  DUPLICATE_UPLOAD_FILE_NAME: new ExceptionCode(
    'duplicateUploadFileName',
    4024,
    "Please DON'T upload duplicate file name. Thank you.",
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  UPLOAD_FILE_SIZE_EXCEED: new ExceptionCode(
    'uploadFileSizeExceed',
    4025,
    'The maximun size for file uploads is 1 GB.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  MAX_SAMPLE_EXCEED: new ExceptionCode(
    'maxSampleExceed',
    4026,
    'Sorry currently there are already 10 sample running in parallel, please wait a while and upload again. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  UPLOAD_VCF_PED_FORMAT_INCORRECT: new ExceptionCode(
    'uploadVcfPedFormatIncorrect',
    4027,
    'The pedigree in VCF file format is not correct. Please follow the https://samtools.github.io/hts-specs/VCFv4.4.pdf and gzip it. For pedigree, please follow the Father, Mother style. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  UPLOAD_VCF_PED_ID_NOT_MATCH: new ExceptionCode(
    'uploadVcfPedIdNotMatch',
    4028,
    'The pedigree in VCF file does not match the sample id in VCF header. Please follow the https://samtools.github.io/hts-specs/VCFv4.4.pdf and gzip it. For pedigree, please follow the Father, Mother style. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  ENTER_HPO_TERMS_FORMAT_INVALID: new ExceptionCode(
    'enterHpoTermsFormatInvalid',
    4029,
    'The input hpo terms format invalid, please use either ["\t"," ", ","] as delimiter and in csv format. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  ERROR_CALLING_ARGO: new ExceptionCode(
    'errorCallingArgo',
    4030,
    'There is error when triggering workflow, please try again. Thank you.',
    EXCEPTION_TYPE.UNEXPECTED,
    EXCEPTION_LEVEL.CRITICAL,
  ),
  NO_PROBAND_IN_PED: new ExceptionCode(
    'noProbandInPed',
    4031,
    'There is no proband ID in ped, please verify and upload again. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  MAX_EXOMISER_RUN_EXCEED: new ExceptionCode(
    'maxExomiserRunExceed',
    4032,
    'Sorry currently there are already 5 exomiser running in parallel, please wait a while and upload again. Thank you.',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
  NO_HPO_ON_INIT: new ExceptionCode(
    'noHPOOnInit',
    4033,
    'No HPO terms on init, therefore no need to run exomiser',
    EXCEPTION_TYPE.REQUEST_ERROR,
    EXCEPTION_LEVEL.NORMAL,
  ),
};

export const DEFAULT_ERROR_MESSAGE = 'Error occurred. Please contact admin.';
