import filtersSlider from '@/models/variants-table/filter/common/filters_slider.json'

const FILTERS_DEFAULT = {
  /** Location text search **/
  geneLocationSearchText: '',

  /** scenario **/ /** SNV & SV **/ scenario: 'none',
  scenarioSelected: 'none',

  /** frequency **/ /** SNV & SV **/ highest_af: 5,
  gnomadv2e_af: 5,
  gnomadv2e_afr_af: 5,
  gnomadv2e_amr_af: 5,
  gnomadv2e_asj_af: 5,
  gnomadv2e_eas_af: 5,
  gnomadv2e_fin_af: 5,
  gnomadv2e_nfe_af: 5,
  gnomadv2e_oth_af: 5,
  gnomadv2e_sas_af: 5,
  gnomadv2g_af: 5,
  gnomadv2g_afr_af: 5,
  gnomadv2g_amr_af: 5,
  gnomadv2g_asj_af: 5,
  gnomadv2g_eas_af: 5,
  gnomadv2g_fin_af: 5,
  gnomadv2g_nfe_af: 5,
  gnomadv2g_oth_af: 5,
  gnomadv2g_sas_af: 5,
  gnomadv3g_af: 5,
  gnomadv3g_afr_af: 5,
  gnomadv3g_amr_af: 5,
  gnomadv3g_asj_af: 5,
  gnomadv3g_eas_af: 5,
  gnomadv3g_fin_af: 5,
  gnomadv3g_mid_af: 5,
  gnomadv3g_nfe_af: 5,
  gnomadv3g_oth_af: 5,
  gnomadv3g_sas_af: 5,
  gnomadv4e_af: 5,
  gnomadv4e_afr_af: 5,
  gnomadv4e_amr_af: 5,
  gnomadv4e_asj_af: 5,
  gnomadv4e_eas_af: 5,
  gnomadv4e_fin_af: 5,
  gnomadv4e_mid_af: 5,
  gnomadv4e_nfe_af: 5,
  gnomadv4e_oth_af: 5,
  gnomadv4e_sas_af: 5,
  gnomadv4g_af: 5,
  gnomadv4g_afr_af: 5,
  gnomadv4g_amr_af: 5,
  gnomadv4g_asj_af: 5,
  gnomadv4g_eas_af: 5,
  gnomadv4g_fin_af: 5,
  gnomadv4g_mid_af: 5,
  gnomadv4g_nfe_af: 5,
  gnomadv4g_oth_af: 5,
  gnomadv4g_sas_af: 5,
  dgv_gold_outer: 5,
  dgv_gold_inner: 5,
  hkbc: 5,
  one_kg_eas: 5,
  one_kg_sur_eas: 5,
  one_kg: 5,
  one_kg_sur: 5,
  gnomadv2_sv_af: 5,
  gnomadv2_sv_afr_af: 5,
  gnomadv2_sv_amr_af: 5,
  gnomadv2_sv_eas_af: 5,
  gnomadv2_sv_eur_af: 5,
  gnomadv2_sv_oth_af: 5,
  gnomadv4_sv_af: 5,
  gnomadv4_sv_afr_af: 5,
  gnomadv4_sv_ami_af: 5,
  gnomadv4_sv_amr_af: 5,
  gnomadv4_sv_asj_af: 5,
  gnomadv4_sv_eas_af: 5,
  gnomadv4_sv_fin_af: 5,
  gnomadv4_sv_mid_af: 5,
  gnomadv4_sv_nfe_af: 5,
  gnomadv4_sv_oth_af: 5,
  gnomadv4_sv_sas_af: 5,
  han_sv_af: 5,

  /** quality **/ /** SV **/ pass_filter: [],
  quality: 0,

  /** impact > both **/
  splice_class: [],
  highest_splice_ai: 0,
  spliceai_pred_ds_ag: 0,
  spliceai_pred_ds_al: 0,
  spliceai_pred_ds_dg: 0,
  spliceai_pred_ds_dl: 0,

  /** impact > snv **/
  snv_type: null,
  is_coding: null,
  is_exonic: null,
  impactHighClick: false,
  impactHighSelected: [],
  impactMedClick: false,
  impactMedSelected: [],
  impactLowClick: false,
  impactLowSelected: [],
  impactModifierClick: false,
  impactModifierSelected: [],
  univar_high_impact: null,

  /** impact > sv **/
  sv_type: null,
  p_lof: [],

  /** pathogenicity **/ /** SNV except Clinical Interpretation  **/ is_pathogenic: null /** SV **/,
  clnsig: [],
  revel: 0,
  cadd_phred: 1,
  cadd_class: [],
  constraint_v2_mis_z: -10,
  constraint_v2_syn_z: -10,
  constraint_v2_oe_lof_upper: 1,
  constraint_v2_oe_mis_upper: 1,
  constraint_v4_mis_z: -20,
  constraint_v4_syn_z: -20,
  constraint_v4_oe_lof_upper: 1,
  constraint_v4_oe_mis_upper: 1,
  PolyphenPredClick: false,
  polyphen_pred: [],
  siftPredClick: false,
  sift_pred: [],
  polyphen_score: 0,
  sift_score: 1,
  clingen_hi: [],
  clingen_ts: [],
  am_class: [],
  am_pathogenicity: 0,
  revel_class: [],

  /** repeats **/ /** SV **/ is_repeat: null,

  /** prioritization **/ /** SNV **/ highest_exomiser_scombi: 0,
  exomiser_ad_exgenescombi: 0,
  exomiser_ar_exgenescombi: 0,
  exomiser_xd_exgenescombi: 0,
  exomiser_xr_exgenescombi: 0,
  exomiser_mt_exgenescombi: 0,
  highest_exomiser_spheno: 0,
  exomiser_ad_exgenespheno: 0,
  exomiser_ar_exgenespheno: 0,
  exomiser_xd_exgenespheno: 0,
  exomiser_xr_exgenespheno: 0,
  exomiser_mt_exgenespheno: 0,

  highest_exomiser_gene_combined_score: 0,
  highest_exomiser_gene_pheno_score: 0,

  /** others **/ /** SV **/ is_read: null,
  note: null,
  variant_type: null,
  len: 3,
  caller: null,
  supp: 0,

  /** slider custom input control **/
  slider: filtersSlider
}

export default FILTERS_DEFAULT
